services:
  - type: web
    name: compspace
    env: node
    plan: free  # Escolha outro plano se necessário
    buildCommand: "npm install"
    startCommand: "node server.js"  # Verifique se o arquivo está correto
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: "/"  # Verifique se a rota raiz existe
