services:
  - type: web
    name: compspace
    env: node
    plan: free  # Você pode escolher outros planos pagos
    buildCommand: "npm install"
    startCommand: "node server.js"  # Altere para o arquivo principal do seu servidor (ex: app.js ou server.js)
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      - mountPath: /data  # Se precisar de armazenamento persistente
        sizeGB: 1
    autoDeploy: true  # Para implantar automaticamente a partir de cada push no Git
    healthCheckPath: "/"  # Verifica a saúde do serviço, altere conforme necessário
    regions:
      - oregon  # Ou outra região disponível mais próxima
    branches:
      only:
        - main  # Ou a branch que você deseja monitorar para deploys automáticos

